const prettier = {
  arrowParens: 'always',
  bracketSameLine: true,
  bracketSpacing: false,
  endOfLine: 'lf',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  htmlWhitespaceSensitivity: 'css',
  proseWrap: 'preserve',
  insertPragma: false,
  printWidth: 80,
  requirePragma: false,
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '^@/types/(.*)$',
    '^@/config/(.*)$',
    '^@/lib/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/ui/(.*)$',
    '^@/components/(.*)$',
    '^@/styles/(.*)$',
    '^/shared-core/provider/(.*)$',
    '^@/shared-core/app/(.*)$',
    '^@/shared-core/types/(.*)$',
    '^@/shared-core/config/(.*)$',
    '^@/shared-core/lib/(.*)$',
    '^@/shared-core/hooks/(.*)$',
    '^@/shared-core/components/ui/(.*)$',
    '^@/shared-core/components/(.*)$',
    '^/shared-core/styles/(.*)$',

    '^@/app/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
}

export default prettier
/** @type {import('prettier').Config} */
module.exports = prettier
